# Generated by Django 4.2.2 on 2023-06-30 23:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("livraria", "0004_livro"),
    ]

    operations = [
        migrations.AddField(
            model_name="livro",
            name="autores",
            field=models.ManyToManyField(related_name="livros", to="livraria.autor"),
        ),
    ]
